# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      /usr/local/bin/helm version --client --short
      /usr/local/bin/helm version repo add stable https://charts.heml.sh/stable
      /usr/local/bin/helm version repo update
    displayName: 'Helm init'
  - task: HelmDeploy@0
    displayName: 'Helm install mysql'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'ainhab-serviceaccount-connection'
      namespace: 'default'
      command: 'install'
      chartType: 'Name'
      chartName: 'stable/mysql'
      overrideValues: 'mysqlpassword=secretpassword'
  - task: HelmDeploy@0
    displayName: 'Helm List'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'ainhab-serviceaccount-connection'
      namespace: 'default'
      command: 'ls'
      arguments: '-a'