apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eadlab3.fullname" . }}
  labels:
    {{- include "eadlab3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eadlab3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eadlab3.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["apt-get update && apt-get install mysql-client -y"]
          resources: {}