apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eadlab3.fullname" . }}
  labels:
    {{- include "eadlab3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eadlab3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eadlab3.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eadlab3.serviceAccountName" . }}
      volumes:
        - name: db-scripts
          configMap:
            name: db-scripts-configmap
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ead-lab3-mysql
                  key: mysql-root-password
          env:
            - name: mysql-host
              value: ead-lab3-mysql
          command: ["/bin/sleep", "3650d"] 
          volumeMounts:
            - name: db-scripts
              mountPath: /tmp
